# Generated by Django 2.1.5 on 2019-02-14 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0002_auto_20190214_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.BigIntegerField(blank=True, default=None, null=True),
        ),
    ]
