# Generated by Django 2.1.5 on 2019-02-17 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0006_category_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(choices=[('AS', 'Aseo'), ('BE', 'Bebidas'), ('AL', 'Bebidas Alcoholicas')], max_length=2),
        ),
    ]
