# Generated by Django 2.1.5 on 2019-02-17 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0009_auto_20190217_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_image',
            field=models.ImageField(default=models.CharField(max_length=30), upload_to='static/'),
        ),
    ]
