# Generated by Django 2.1.5 on 2019-02-20 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0014_auto_20190220_1747'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_id', models.AutoField(primary_key=True, serialize=False)),
                ('department_name', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('bar_code', models.BigIntegerField(primary_key=True, serialize=False)),
                ('plu', models.IntegerField(null=True)),
                ('name', models.CharField(max_length=100)),
                ('cost', models.IntegerField(null=True)),
                ('normal_price', models.IntegerField(null=True)),
                ('m_com', models.FloatField(null=True)),
                ('m_uti', models.FloatField(null=True)),
                ('offer_price', models.IntegerField(null=True)),
                ('stock', models.IntegerField(null=True)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='back.Department')),
            ],
        ),
    ]
