# Generated by Django 2.1.3 on 2019-02-14 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='cargo',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='contact',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='contact',
            name='numero',
            field=models.IntegerField(blank=True, default=None),
        ),
    ]
