# Generated by Django 2.1.3 on 2019-02-14 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0003_auto_20190214_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='numero',
            field=models.CharField(blank=True, default=None, max_length=30),
        ),
    ]
